
function( mpb_library_add_shared name )
    message( "Building SHARED library: ${name}" )
    list( REMOVE_AT ARGV 0 )
    add_library( ${name} SHARED ${ARGV} )
endfunction( mpb_library_add_shared name )

function( mpb_library_add_static name )
    message( "Building STATIC library: ${name}" )
    list( REMOVE_AT ARGV 0 )
    add_library( ${name} STATIC ${ARGV} )
endfunction( mpb_library_add_static name )

function( mpb_library_add name )
    if( DEFINED ${name}_STATIC OR DEFINED MPB_ALL_STATIC )
        list( REMOVE_AT ARGV 0 )
        mpb_library_add_static( ${name} ${ARGV} )
    else( DEFINED ${name}_STATIC OR DEFINED MPB_ALL_STATIC )
        list( REMOVE_AT ARGV 0 )
        mpb_library_add_shared( ${name} ${ARGV} )
    endif( DEFINED ${name}_STATIC OR DEFINED MPB_ALL_STATIC )
endfunction( mpb_library_add name )

function( mpb_library_set_includes name includes )
    string( TOUPPER name _name )
    set( ${_name}_INCLUDES ${includes} )
endfunction( mpb_library_set_includes name includes )

function( mpb_library_set_cflags name flags )
    string( TOUPPER name _name )
    set( ${_name}_CFLAGS ${flags} )
endfunction( mpb_library_set_cflags name flags )

function( mpb_library_set_lflags name flags )
    string( TOUPPER name _name )
    set( ${_name}_LFLAGS ${flags} )
endfunction( mpb_library_set_lflags name flags )

function( mpb_library_export name )
    string( TOUPPER name _name )
    set( ${_name}_INCLUDES ${_name}_INCLUDES PARENT_SCOPE )
    set( ${_name}_CFLAGS ${_name}_CFLAGS PARENT_SCOPE )
    set( ${_name}_LFLAGS ${_name}_LFLAGS PARENT_SCOPE )
endfunction( mpb_library_export name )
